InsightHub/InsightHub/Controllers/Admin/AdminUserController.cs
using Microsoft.AspNetCore.Http.Extensions;
using InsightHub.Web.WebMappers.Contracts;
using InsightHub.Services.Contracts;
using InsightHub.Services.DTOs;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using InsightHub.Web.Models;
using NToastNotify;
using System;
using Microsoft.AspNetCore.Authorization;

namespace InsightHub.Web.Controllers.Admin
{
    /// <summary>
    /// This class contains methods for working with user
    /// that only the admin can invoke
    /// </summary>
    [Authorize(Roles = "Admin")]
    public class AdminUserController : Controller
    {
        private readonly IMailer mailer;
        private readonly IBanService banService;
        private readonly IUserService userService;
        private readonly IToastNotification toastNotification;
        private readonly IViewModelMapper<BanDTO, BanViewModel> banMapper;
        private readonly IViewModelMapper<UserDTO, UserViewModel> userMapper;

        public AdminUserController(IUserService userService, IMailer mailer,
            IBanService banService, IToastNotification toastNotification, IViewModelMapper<UserDTO,
            UserViewModel> userMapper, IViewModelMapper<BanDTO, BanViewModel> banMapper)
        {
            this.mailer = mailer ?? throw new ArgumentNullException(nameof(mailer));
            this.banMapper = banMapper ?? throw new ArgumentNullException(nameof(banMapper));
            this.userMapper = userMapper ?? throw new ArgumentNullException(nameof(userMapper));
            this.banService = banService ?? throw new ArgumentNullException(nameof(banService));
            this.userService = userService ?? throw new ArgumentNullException(nameof(userService));
            this.toastNotification = toastNotification ?? throw new ArgumentNullException(nameof(toastNotification));
        }

        [HttpGet]
        public async Task<IActionResult> GetUser(int id)
        {
            try
            {
                var user = await this.userService.GetUserAsync(id);
                return View(user);
            }
            catch (Exception)
            {
                this.toastNotification.AddWarningToastMessage("Oops! Something went wrong. Please try again");
                return View();
            }
        }

        [HttpGet]
        public async Task<IActionResult> GetApprovedUsers()
        {
            var unbannedUsers = await this.userService.GetAllValidUsersAsync();
            var bannedUsers = await this.banService.GetAllBannedUsersAsync();
            var unbannedUsersVM = this.userMapper.MapFrom(unbannedUsers);
            var bannedUserVM = this.userMapper.MapFrom(bannedUsers);
            ViewData["unbannedUsersVM"] = unbannedUsersVM;
            ViewData["bannedUsersVM"] = bannedUserVM;

            return View();
        }

        [HttpGet]
        public IActionResult BanUser()
        {

            return View();
        }
 
        [HttpPost]
        public async Task<IActionResult> BanUser(BanViewModel banVM)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    this.toastNotification.AddErrorToastMessage("Model state is not valid.");
                    return RedirectToAction(nameof(GetApprovedUsers));
                }

                string url = Request.GetDisplayUrl();
                var tokens = url.Split('/');
                var userId = int.Parse(tokens[tokens.Length - 1]);
                banVM.UserId = userId;

                var banDTO = this.banMapper.MapFrom(banVM);
                await this.banService.CreateBanAsync(banDTO);

                this.toastNotification.AddSuccessToastMessage("Ban was successfully created");
                return RedirectToAction("GetApprovedUsers");
            }
            catch (Exception e)
            {
                this.toastNotification.AddErrorToastMessage(e.Message);
                return View();
            }
        }
   
        public async Task<IActionResult> UnbanUserConfirm(int? id)
        {
            try
            {
                if (id == null)
                {
                    this.toastNotification.AddErrorToastMessage("Id cannot be null");
                    return RedirectToAction(nameof(GetApprovedUsers));
                }

                await this.banService.RemoveBanAsync(id);

                this.toastNotification.AddSuccessToastMessage("Ban was successfully removed");
                return RedirectToAction("GetApprovedUsers");
            }
            catch (Exception e)
            {
                this.toastNotification.AddErrorToastMessage(e.Message);
                return View();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var report = await this.userService.DeleteUserAsync(id);
            this.toastNotification.AddAlertToastMessage("User successfully deleted");
            return RedirectToAction(nameof(GetApprovedUsers));
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int? id)
        {
            if (id == null)
            {
                return NotFound("Id cannot be null or empty");
            }

            var user = await this.userService.GetUserAsync(id.Value);

            if (user == null)
            {
                return NotFound("User cannot be null or empty");
            }

            return View(user);
        }

        [HttpGet]
        public async Task<IActionResult> GetUsersForApproval()

        {
            var pendingUsers = (await this.userService.GetPendingUsersAsync());
            var pendingUsersVM = this.userMapper.MapFrom(pendingUsers);
            ViewData["pendingUsersVM"] = pendingUsersVM;

            return View();
        }

        public async Task<IActionResult> ApproveUserConfirm(int? id)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    ModelState.AddModelError(string.Empty, "Model state is not valid.");
                }

                var pendingUsers = await this.userService.AproveUserAsync(id);

                this.toastNotification.AddInfoToastMessage("User will be notified by email from Insight Hub Team");
                this.toastNotification.AddSuccessToastMessage("Registration was successfully approved");
                return RedirectToAction("GetUsersForApproval");
            }
            catch (Exception e)
            {
                this.toastNotification.AddErrorToastMessage(e.Message);
                return View();
            }
        }

        public async Task<IActionResult> RejectUserConfirm(int? id)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    ModelState.AddModelError(string.Empty, "Model state is not valid.");
                }

                //TODO: hard delete
                var pendingUsers = await this.userService.GetUserAsync(id);
                await this.userService.DeleteUserAsync(id);

                this.toastNotification.AddInfoToastMessage("User will be notified by email from Insight Hub Team");
                this.toastNotification.AddWarningToastMessage("Account registration was rejected");
                await mailer.UserRejected(pendingUsers.Email);
                return RedirectToAction("GetUsersForApproval");
            }
            catch (Exception e)
            {
                this.toastNotification.AddErrorToastMessage(e.Message);
                return View();
            }
        }
    }
}

InsightHub/InsightHub/Controllers/Common/CommonController.cs
using InsightHub.Web.WebMappers.Contracts;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using InsightHub.Services.Contracts;
using System.Collections.Generic;
using InsightHub.Services.DTOs;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Threading.Tasks;
using InsightHub.Web.Models;
using NToastNotify;
using System.Linq;
using System;

namespace InsightHub.Web.Controllers.Common
{
    public class CommonController : Controller
    {
        private readonly ITagService tagService;
        private readonly IReportService reportService;
        private readonly IIndustryService industryService;
        private readonly IToastNotification toastNotification;
        private readonly IViewModelMapper<TagDTO, TagViewModel> tagMapper;
        private readonly IViewModelMapper<ReportDTO, ReportViewModel> reportMapper;
        private readonly IViewModelMapper<IndustryDTO, IndustryViewModel> industryMapper;

        public CommonController(IReportService reportService,
            IViewModelMapper<ReportDTO, ReportViewModel> reportMapper,
            IViewModelMapper<IndustryDTO, IndustryViewModel> industryMapper,
            IToastNotification toastNotification, IIndustryService industryService,
            IViewModelMapper<TagDTO, TagViewModel> tagMapper, ITagService tagService)
        {
            this.toastNotification = toastNotification ?? throw new ArgumentNullException(nameof(toastNotification));
            this.industryService = industryService ?? throw new ArgumentNullException(nameof(industryService));
            this.industryMapper = industryMapper ?? throw new ArgumentNullException(nameof(industryMapper));
            this.reportService = reportService ?? throw new ArgumentNullException(nameof(reportService));
            this.reportMapper = reportMapper ?? throw new ArgumentNullException(nameof(reportMapper));
            this.tagService = tagService ?? throw new ArgumentNullException(nameof(tagService));
            this.tagMapper = tagMapper ?? throw new ArgumentNullException(nameof(tagMapper));
        }

        [HttpGet]
        [Authorize(Roles = "Admin, Author")]
        public async Task<IActionResult> CreateReport()

        {
            var tags = await tagService.GetAllTagsAsync();
            var tagsVM = this.tagMapper.MapFrom(tags);
            var selectList = new List<SelectListItem>();
            var tagsVMList = tagsVM.ToList();

            tagsVMList.ForEach(i => selectList.Add(new SelectListItem(i.Name, i.Id.ToString())));
            var mapToSelectList = new ReportViewModel() { Tags = selectList };

            ViewData["Id"] = new SelectList(await industryService.GetAllIndustries(), "Id", "Name");
            return View(mapToSelectList);
        }

        [HttpPost]
        [Authorize(Roles = "Author, Admin")]
        public async Task<IActionResult> CreateReport(ReportViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    this.toastNotification.AddErrorToastMessage("Model state is not valid.");
                    return RedirectToAction(nameof(CreateReport));
                }
                model.AuthorId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
                var modelToDTO = this.reportMapper.MapFrom(model);
                await this.reportService.CreateReportAsync(modelToDTO);

                this.toastNotification.AddSuccessToastMessage("Report successfully created. You will be notified " +
                    "by email from Insight Hub Team, when the report is approved");
                return RedirectToAction(nameof(CreateReport));
            }
            catch (Exception e)
            {
                this.toastNotification.AddErrorToastMessage(e.Message);
                return RedirectToAction(nameof(CreateReport));
            }
        }

        [HttpGet]
        [Authorize(Roles = "Author, Admin")]
        public async Task<IActionResult> UpdateReport(int? id)

        {
            var report = await reportService.GetReportAsync(id.Value);
            var tags = await tagService.GetAllTagsAsync();
            var tagsVM = this.tagMapper.MapFrom(tags);
            var selectList = new List<SelectListItem>();
            var tagsVMList = tagsVM.ToList();

            tagsVMList.ForEach(i => selectList.Add(new SelectListItem(i.Name, i.Id.ToString())));
            var mapToSelectList = new ReportViewModel() { Tags = selectList };

            ViewData["Id"] = new SelectList(await industryService.GetAllIndustries(), "Id", "Name");
            var reportVM = reportMapper.MapFrom(report);
            reportVM.Tags = selectList;
            ViewData["Model"] = reportVM;
            return View(reportVM);
        }

        [HttpPost]
        [Authorize(Roles = "Admin, Author")]
        public async Task<IActionResult> UpdateReport(int? id, ReportViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    ModelState.AddModelError(string.Empty, "Model state is not valid.");
                }

                var modelToDTO = this.reportMapper.MapFrom(model);
                await this.reportService.UpdateReportAsync(modelToDTO);
                this.toastNotification.AddSuccessToastMessage("Report successfully updated");
                return RedirectToAction(nameof(UpdateReport));
            }

            catch (Exception e)
            {
                this.toastNotification.AddErrorToastMessage(e.Message);
                return RedirectToAction(nameof(UpdateReport));
            }
        }

        [HttpGet]
        [Authorize(Roles = "Author, Admin")]
        public IActionResult CreateTag()

        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Author, Admin")]
        public async Task<IActionResult> CreateTag(TagViewModel model)
        {
            if (ModelState.IsValid)
            {
                var modelToDTO = this.tagMapper.MapFrom(model);
                await this.tagService.CreateTagAsync(modelToDTO);
                this.toastNotification.AddSuccessToastMessage("Tag successfully created");

                return RedirectToAction(nameof(CreateReport));
            }

            this.toastNotification.AddWarningToastMessage("Incorrect input, please try again");
            ModelState.AddModelError(string.Empty, "Model state is not valid.");
            return RedirectToAction("CreateTag");
        }

        [HttpGet]
        [Authorize(Roles = "Author, Admin")]
        public async Task<IActionResult> UpdateTagAsync(int? id)
        {
            try
            {
                var tag = await this.tagService.GetTagAsync(id.Value);
                var modelToDTO = this.tagMapper.MapFrom(tag);
                return View(modelToDTO);
            }
            catch (Exception)
            {
                this.toastNotification.AddWarningToastMessage("Oops! Something went wrong. Please try again");
                return View();
            }
        }

        [HttpPost]
        [Authorize(Roles = "Author, Admin")]
        public async Task<IActionResult> UpdateTag(TagViewModel model)
        {
            if (ModelState.IsValid)
            {
                var modelToDTO = this.tagMapper.MapFrom(model);
                await this.tagService.UpdateTagAsync(modelToDTO);
                this.toastNotification.AddSuccessToastMessage("Tag successfully updated");
                return RedirectToAction("GetAllTags", "AdminTag"); 
            }

            this.toastNotification.AddWarningToastMessage("Incorrect input, please try again");
            ModelState.AddModelError(string.Empty, "Model state is not valid.");
            return RedirectToAction("UpdateTag");
        }
    }
}

InsightHub/InsightHub/Views/Shared/_Contact.cshtml
    <!-- Contact -->
<div id="contact" class="form-2">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2>Contact Information</h2>
                <ul class="list-unstyled li-space-lg">
                    <li class="address">Don't hesitate to give us a call or send us a contact form message</li>
                    <li><i class="fas fa-map-marker-alt"></i>22 Innovative Area, San Francisco, CA 94043, US</li>
                    <li><i class="fas fa-phone"></i><a class="turquoise" href="tel:003024630820">+81 720 2212</a></li>
                    <li><i class="fas fa-envelope"></i><a class="turquoise" href="mailto:insighthubproject@gmail.com">office@insighthubproject.com</a></li>
                </ul>
            </div> <!-- end of col -->
        </div> <!-- end of row -->
        <div class="row">
            <div class="col-lg-6">
                <div class="map-responsive">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d100939.98555098464!2d-122.507640204439!3d37.757814996609724!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80859a6d00690021%3A0x4a501367f076adff!2sSan+Francisco%2C+CA%2C+USA!5e0!3m2!1sen!2sro!4v1498231462606" allowfullscreen></iframe>
                </div>
            </div> <!-- end of col -->
            <div class="col-lg-6">

                <!-- Contact Form -->
                <form id="contactForm" data-toggle="validator" data-focus="false">
                    <div class="form-group">
                        <input type="text" class="form-control-input" id="cname" required>
                        <label class="label-control" for="cname">Name</label>
                        <div class="help-block with-errors"></div>
                    </div>
                    <div class="form-group">
                        <input type="email" class="form-control-input" id="cemail" required>
                        <label class="label-control" for="cemail">Email</label>
                        <div class="help-block with-errors"></div>
                    </div>
                    <div class="form-group">
                        <textarea class="form-control-textarea" id="cmessage" required></textarea>
                        <label class="label-control" for="cmessage">Your message</label>
                        <div class="help-block with-errors"></div>
                    </div>
                    <div class="form-group checkbox">
                        <input type="checkbox" id="cterms" value="Agreed-to-Terms" required>I have read and agree with Evolo's stated <a href="privacy-policy.html">Privacy Policy</a> and <a href="terms-conditions.html">Terms Conditions</a>
                        <div class="help-block with-errors"></div>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="form-control-submit-button">SUBMIT MESSAGE</button>
                    </div>
                    <div class="form-message">
                        <div id="cmsgSubmit" class="h3 text-center hidden"></div>
                    </div>
                </form>
                <!-- end of contact form -->

            </div> <!-- end of col -->
        </div> <!-- end of row -->
    </div> <!-- end of container -->
</div> <!-- end of form-2 -->
<!-- end of contact -->

InsightHub/InsightHub/Views/Shared/_Role_Restriction_Nav.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager﻿

@{
    var url = Url.Content("");
}
<nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top" style="background-image: url(/images/clear-impact-state-government-background-header.jpg);">
    <!-- Text Logo - Use this if you don't have a graphic logo -->
    <a class="navbar-brand logo-text page-scroll" href="@Url.Action("Index", "Home")">Insight Hub</a>
    <!-- Image Logo -->
    <!-- <a class="navbar-brand logo-image" href="index.html"><img src="images/logo.png" alt="alternative"></a> -->
    <!-- Mobile Menu Toggle Button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-awesome fas fa-bars"></span>
        <span class="navbar-toggler-awesome fas fa-times"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link page-scroll" href="@Url.Action("Index", "Home")">Home <span class="sr-only">(current)</span></a>
            </li>
            <!-- Dashboard -->
            @if (User.IsInRole("Admin"))
            {
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle page-scroll" id="navbarDropdown" role="button" aria-haspopup="true" aria-expanded="false">Featured</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        @if (url != "~/")
                        {
                            <a class="dropdown-item" href="~/#recommended"><span class="item-text">Public Featured</span></a>
                        }
                        else
                        {
                            <a class="dropdown-item" href="#recommended">Public Featured</a>
                        }
                        <div class="dropdown-items-divide-hr"></div>
                        <a class="dropdown-item" asp-controller="AdminReport" asp-action="FeaturedReports"><span class="item-text">Feature</span></a>
                    </div>
                </li>
                <li class="nav-item">
                    @if (url != "~/")
                    {
                        <a class="nav-link page-scroll" href="/#popular">Popular</a>
                    }
                    else
                    {
                        <a class="nav-link page-scroll" href="#popular">Popular</a>
                    }
                </li>
                <li class="nav-item">
                    @if (url != "~/")
                    {
                        <a class="nav-link page-scroll" href="/#new">New</a>
                    }
                    else
                    {
                        <a class="nav-link page-scroll" href="#new">New</a>
                    }
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle page-scroll" href="#about" id="navbarDropdown" role="button" aria-haspopup="true" aria-expanded="false">Tags</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" asp-controller="Common" asp-action="CreateTag"><span class="item-text">Create Tag</span></a>
                        <div class="dropdown-items-divide-hr"></div>
                        <a class="dropdown-item" asp-controller="AdminTag" asp-action="GetAllTags"><span class="item-text">Get All</span></a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle page-scroll" href="#about" id="navbarDropdown" role="button" aria-haspopup="true" aria-expanded="false">Reports</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" asp-controller="AnonymousReport" asp-action="GetAllReports"><span class="item-text">Get All</span></a>
                        <div class="dropdown-items-divide-hr"></div>
                        <a class="dropdown-item" asp-controller="AdminReport" asp-action="GetReportsForApproval"><span class="item-text">Requests for Approval</span></a>
                        <div class="dropdown-items-divide-hr"></div>
                        <a class="dropdown-item" asp-controller="Common" asp-action="CreateReport"><span class="item-text">Create Report</span></a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle page-scroll" href="#about" id="navbarDropdown" role="button" aria-haspopup="true" aria-expanded="false">User</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" asp-controller="AdminUser" asp-action="GetUsersForApproval"><span class="item-text">Registration Approval</span></a>
                        <div class="dropdown-items-divide-hr"></div>
                        <a class="dropdown-item" asp-controller="AdminUser" asp-action="GetApprovedUsers"><span class="item-text">Accounts Ban</span></a>
                    </div>
                </li>
            }
            else if (User.IsInRole("Author"))
            {
                <li class="nav-item">
                    @if (url != "~/")
                    {
                        <a class="nav-link page-scroll" href="/#recommended">Featured</a>
                    }
                    else
                    {
                        <a class="nav-link page-scroll" href="/#recommended">Featured</a>
                    }
                </li>
                <li class="nav-item">
                    @if (url != "~/")
                    {
                        <a class="nav-link page-scroll" href="/#popular">Popular</a>
                    }
                    else
                    {
                        <a class="nav-link page-scroll" href="#popular">Popular</a>
                    }
                </li>
                <li class="nav-item">
                    @if (url != "~/")
                    {
                        <a class="nav-link page-scroll" href="/#new">New</a>
                    }
                    else
                    {
                        <a class="nav-link page-scroll" href="#new">New</a>
                    }
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle page-scroll" href="#about" id="navbarDropdown" role="button" aria-haspopup="true" aria-expanded="false">Tags</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" asp-controller="Common" asp-action="CreateTag"><span class="item-text">Create Tag</span></a>
                        <div class="dropdown-items-divide-hr"></div>
                        <a class="dropdown-item" asp-controller="AdminTag" asp-action="GetAllTags"><span class="item-text">Get All</span></a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle page-scroll" href="#about" id="navbarDropdown" role="button" aria-haspopup="true" aria-expanded="false">Reports</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" asp-controller="AnonymousReport" asp-action="GetAllReports"><span class="item-text">Get All</span></a>
                        <div class="dropdown-items-divide-hr"></div>
                        <a class="dropdown-item" asp-controller="Common" asp-action="CreateReport"><span class="item-text">Create Report</span></a>
                        <div class="dropdown-items-divide-hr"></div>
                        <a class="dropdown-item" asp-controller="AuthorReport" asp-action="GetReportsOfUser"><span class="item-text">My Reports</span></a>
                    </div>
                </li>
            }

            else if (User.IsInRole("Customer"))
            {
                <li class="nav-item">
                    @if (url != "~/")
                    {
                        <a class="nav-link page-scroll" href="/#recommended">Featured</a>
                    }
                    else
                    {
                        <a class="nav-link page-scroll" href="#recommended">Featured</a>
                    }
                </li>
                <li class="nav-item">
                    @if (url != "~/")
                    {
                        <a class="nav-link page-scroll" href="/#popular">Popular</a>
                    }
                    else
                    {
                        <a class="nav-link page-scroll" href="#popular">Popular</a>
                    }
                </li>
                <li class="nav-item">
                    @if (url != "~/")
                    {
                        <a class="nav-link page-scroll" href="/#new">New</a>
                    }
                    else
                    {
                        <a class="nav-link page-scroll" href="#new">New</a>
                    }
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle page-scroll" href="#about" id="navbarDropdown" role="button" aria-haspopup="true" aria-expanded="false">Reports</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" asp-controller="AnonymousReport" asp-action="GetAllReports"><span class="item-text">Get All</span></a>
                        <div class="dropdown-items-divide-hr"></div>
                        <a class="dropdown-item" asp-controller="CustomerReport" asp-action="GetDownloadedReportsByUser"><span class="item-text">Downloaded reports</span></a>
                        <div class="dropdown-items-divide-hr"></div>
                        <a class="dropdown-item" asp-controller="CustomerSubscription" asp-action="GetNonSubscriptionsOfUser"><span class="item-text">Subscribe for email notification</span></a>
                        <div class="dropdown-items-divide-hr"></div>
                        <a class="dropdown-item" asp-controller="CustomerSubscription" asp-action="GetSubscriptionsOfUser"><span class="item-text">Unsubscribe for email notification</span></a>
                    </div>
                </li>
            }

            else
            {
                <li class="nav-item">
                    @if (url != "~/")
                    {
                        <a class="nav-link page-scroll" href="/#recommended">Featured</a>
                    }
                    else
                    {
                        <a class="nav-link page-scroll" href="#recommended">Featured</a>
                    }
                </li>
                <li class="nav-item">
                    @if (url != "~/")
                    {
                        <a class="nav-link page-scroll" href="/#popular">Popular</a>
                    }
                    else
                    {
                        <a class="nav-link page-scroll" href="#popular">Popular</a>
                    }
                </li>
                <li class="nav-item">
                    @if (url != "~/")
                    {
                        <a class="nav-link page-scroll" href="/#new">New</a>
                    }
                    else
                    {
                        <a class="nav-link page-scroll" href="#new">New</a>
                    }
                </li>
                <li class="nav-item">
                    <a class="nav-link page-scroll" asp-controller="AnonymousReport" asp-action="GetAllReports">Reports</a>
                </li>

            }
            <partial name="_LoginPartial" />

        </ul>
        <span class="nav-item social-icons">
            <span class="fa-stack">
                <a href="#your-link">
                    <i class="fas fa-circle fa-stack-2x facebook"></i>
                    <i class="fab fa-facebook-f fa-stack-1x"></i>
                </a>
            </span>
            <span class="fa-stack">
                <a href="#your-link">
                    <i class="fas fa-circle fa-stack-2x twitter"></i>
                    <i class="fab fa-twitter fa-stack-1x"></i>
                </a>
            </span>
        </span>
    </div>
</nav>