InsightHub/InsightHub/Controllers/Anonymous/AnonymousReportController.cs
using InsightHub.Web.WebMappers.Contracts;
using Microsoft.AspNetCore.Authorization;
using InsightHub.Services.Contracts;
using InsightHub.Services.DTOs;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using InsightHub.Web.Models;
using NToastNotify;
using System;

namespace InsightHub.Web.Controllers.Anonymous
{
    /// <summary>
    /// This class contains public part methods for working with reports
    /// </summary>
    [AllowAnonymous]
    public class AnonymousReportController : Controller
    {
        private readonly IReportService reportService;
        private readonly IToastNotification toastNotification;
        private readonly IViewModelMapper<ReportDTO, ReportViewModel> reportMapper;

        public AnonymousReportController(IReportService reportService,
            IViewModelMapper<ReportDTO, ReportViewModel> reportMapper,
            IToastNotification toastNotification)
        {
            this.reportService = reportService ?? throw new ArgumentNullException(nameof(reportService));
            this.toastNotification = toastNotification ?? throw new ArgumentNullException(nameof(toastNotification));
            this.reportMapper = reportMapper ?? throw new ArgumentNullException(nameof(reportMapper));
        }

        [HttpGet]
        public async Task<IActionResult> GetAllReports()
        {
            try
            {
                var reports = await this.reportService.GetAprovedReportsAsync();
                var reportsVM = this.reportMapper.MapFrom(reports);

                return View(reportsVM);
            }
            catch (Exception)
            {
                this.toastNotification.AddWarningToastMessage("Oops! Something went wrong. Please try again");
                return View();
            }
        }

        [HttpGet]
        public async Task<IActionResult> GetReport(int id)
        {
            try
            {
                var report = await this.reportService.GetReportAsync(id);
                return View(report);
            }
            catch (Exception)
            {
                this.toastNotification.AddWarningToastMessage("Oops! Something went wrong. Please try again");
                return View();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound("Id cannot be null or empty");
            }

            var report = await this.reportService.GetReportAsync(id.Value);

            if (report == null)
            {
                return NotFound("Report cannot be null or empty");
            }

            return View(reportMapper.MapFrom(report));
        }
    }
}

InsightHub/InsightHub/Controllers/Customer/CustomerReportController.cs
using InsightHub.Web.WebMappers.Contracts;
using Microsoft.AspNetCore.Authorization;
using InsightHub.Services.Contracts;
using InsightHub.Services.DTOs;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using System.Security.Claims;
using InsightHub.Web.Models;
using NToastNotify;
using System;

namespace InsightHub.Web.Controllers.Customer
{
    [Authorize(Roles = "Customer")]
    public class CustomerReportController : Controller
    {
        private readonly IBlobService blobService;
        private readonly IReportService reportService;
        private readonly IToastNotification toastNotification;
        private readonly IViewModelMapper<ReportDTO, ReportViewModel> reportMapper;

        public CustomerReportController(IReportService reportService,
            IViewModelMapper<ReportDTO, ReportViewModel> reportMapper,
            IToastNotification toastNotification, IBlobService blobService)
        {
            this.blobService = blobService ?? throw new ArgumentNullException(nameof(blobService));
            this.reportMapper = reportMapper ?? throw new ArgumentNullException(nameof(reportMapper));
            this.reportService = reportService ?? throw new ArgumentNullException(nameof(reportService));
            this.toastNotification = toastNotification ?? throw new ArgumentNullException(nameof(toastNotification));
        }

        [HttpGet]
        public async Task<IActionResult> DownloadReport(int? id)
        {
            try
            {
                var downloaderId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
                var report = await this.reportService.DownloadReportAsync(downloaderId, id);
                var reportsVM = this.reportMapper.MapFrom(report);
                var data = await blobService.GetBlobAsync(report.Name + ".pdf");
                return File(data.Content, data.ContentType);
            }

            catch (Exception e)
            {
                this.toastNotification.AddErrorToastMessage(e.Message);
                return RedirectToAction("GetDownloadedReportsByUser");
            }
        }

        public async Task<IActionResult> GetDownloadedReportsByUser()
        {
            try
            {
                var user = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
                var reports = await this.reportService.GetDownloadedReportsByUserAsync(user);
                var reportsVM = this.reportMapper.MapFrom(reports);
                return View(reportsVM);
            }

            catch (Exception e)
            {
                this.toastNotification.AddErrorToastMessage(e.Message);
                return View();
            }
        }
    }
}

InsightHub/InsightHub/Views/AnonymousReport/Details.cshtml
@model InsightHub.Web.Models.ReportViewModel

<style>
    .header-content {
        width: 1000px;
        margin-left: 400px;
    }

    h1 {
        text-align: center
    }

    h4 {
        text-align: center;
    }

    .btn {
    }
</style>

<h4>"@Model.Name"</h4>
<div class="col text-center">
    <a asp-controller="CustomerReport" asp-action="DownloadReport" asp-route-id="@Model.Id"
       class="btn btn-danger btn btn-default" style="text-decoration:none"><i class="fas fa-file-download"></i>Download report</a>
</div>

<div>
    <hr />
    <dl class="row" style="justify-content: center;">
        <dd>
            <img src="~/images/Industries/@Html.DisplayFor(model =>model.IndustryImg)" style="height:500px;width:720px;" />
        </dd>
        <dt class="col-lg-8">
            @Html.DisplayNameFor(model => model.Summary)
        </dt>
        <dd class="col-lg-8">
            @Html.DisplayFor(model => model.Summary)
        </dd>
        <dt class="col-lg-8">
            @Html.DisplayNameFor(model => model.AuthorName)
        </dt>
        <dd class="col-lg-8">
            @Html.DisplayFor(model => model.AuthorName)
        </dd>
        <dt class="col-lg-8">
            @Html.DisplayNameFor(model => model.IndustryName)
        </dt>
        <dd class="col-lg-8">
            @Html.DisplayFor(model => model.IndustryName)
        </dd>
        <dt class="col-lg-8">
            @Html.DisplayNameFor(model => model.DownloadsCnt)
        </dt>
        <dd class="col-lg-8">
            @Html.DisplayFor(model => model.DownloadsCnt)
        </dd>
        <dt class="col-lg-8">
            @Html.DisplayNameFor(model => model.TagNames)
        </dt>
        <dd class="col-lg-8">
            @String.Join(", ", Model.TagNames)
        </dd>
        <dt class="col-lg-8">
            @Html.DisplayNameFor(model => model.UploadedOn)
        </dt>
        <dd class="col-lg-8">
            @Html.DisplayFor(model => model.UploadedOn)
        </dd>
    </dl>
</div>
<partial name="_GoBack" />

InsightHub/InsightHub/Views/AnonymousReport/GetAllReports.cshtml
@model IEnumerable<InsightHub.Web.Models.ReportViewModel>
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager﻿
@using Microsoft.AspNetCore.Identity

<style>
    .table tr {
        cursor: pointer;
    }

    .hiddenRow {
        padding: 0 4px !important;
        background-color: #eeeeee;
        font-size: 13px;
    }

    #table {
        pointer-events: none;
    }
</style>

<div class="container" style="display:contents">
    <br />
    <div style="width: 90%; margin: 0 auto;">
        <table id="search" data-toolbar="#toolbar" class="table table-striped table-bordered dt-responsive nowrap" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>Id</th>
                    <th id="table">Img</th>
                    <th>Name</th>
                    <th>Summary</th>
                    <th>Author</th>
                    <th>Industry</th>
                    <th>Upload date</th>
                    <th>Downloads count</th>
                    <th id="table">Tags</th>
                    <th id="table">Details</th>
                    @if (User.IsInRole("Customer"))
                    {
                        <th id="table">Download</th>
                    }
                    @if (User.IsInRole("Admin"))
                    {
                        <th id="table">Edit</th>
                        <th id="table">Delete</th>
                    }
                </tr>
            </thead>
        </table>
    </div>
</div>

<script>
    $(document).ready(function() {
        $("#search").DataTable({
            "processing": true, // for show progress bar
            "serverSide": true, // for process server side
            "filter": true, // this is for disable filter (search box)
            "orderMulti": false, // for disable multiple column at once

            "ajax": {
                "url": "/Search/LoadReports",
                "type": "POST",
                "dataSrc": "data"
            },
            "columnDef": [{
                "targets": [0],
                "visible": false,
                "searchable": false
            }],
            "columns": [

                { "data": "id", "name": "id", "industryName": "industry", "autoWidth": true },

                  {
                    data: null,
                      render: function (data, type, full, meta) {
                          { return '<img src="/images/Industries/' + full.industryName + '.jpg' + '" width="250" height="200"/></td>'; }

                      }
                },

                { "data": "name", "name": "name", "autoWidth": true },
                { "data": "summary", "name": "summary", "autoWidth": true },
                { "data": "authorName", "name": "authorName", "autoWidth": true },
                { "data": "industryName", "name": "industryName", "autoWidth": true },
                { "data": "uploadedOn", "name": "uploadedOn", "autoWidth": true },
                { "data": "downloadsCnt", "name": "downloadsCnt", "autoWidth": true },
                { "data": "tagNames", "name": "tagNames", "autoWidth": true },

                    {
                    data: null,
                        render: function (data, type, full, meta) {
                            { return '<a class="btn btn-warning" href="/AnonymousReport/Details/' + full.id + '"><i class="fas fa-info-circle">See more</a>'; }
                        }
                    },

                  @if(User.IsInRole("Customer"))
                  {
                   <text>
                      {
                       data: null,
                       render: function (data, type, full, meta) {
                           { return '<a class="btn btn-warning" href="/CustomerReport/DownloadReport/' + full.id + '"download><i class="fa fa-download">Download</a>'; }
                       }
                    },
                   </text>
                  }


                 @if (User.IsInRole("Admin"))
                  {
                   <text>
                         {
                    data: null,
                        render: function (data, type, full, meta) {
                            {  return '<a class="btn btn-success" href="/Common/UpdateReport/' + full.id + '"><i class="fas fa-user-check">Edit</a>'; }
                        }
                    },
                        {
                       data: null,
                            render: function (data, type, full, meta) {
                               { return '<a class="btn btn-danger" href="/AdminReport/Delete/' + full.id + '"><i class="fa fa-delete alt">Delete</a>'; }
                       }
                    },

                   </text>
                     }
            ]
        });
    });
</script>

<partial name="_GoBack" />