InsightHub/InsightHub/Controllers/Admin/AdminReportController.cs
using InsightHub.Web.WebMappers.Contracts;
using Microsoft.AspNetCore.Authorization;
using InsightHub.Services.Contracts;
using InsightHub.Services.DTOs;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using InsightHub.Web.Models;
using NToastNotify;
using System;

namespace InsightHub.Web.Controllers.Admin
{
    /// <summary>
    /// This class contains methods for working with reports
    /// that only the admin can invoke
    /// </summary>
    [Authorize(Roles = "Admin")]
    public class AdminReportController : Controller
    {
        private readonly IReportService reportService;
        private readonly IToastNotification toastNotification;
        private readonly IViewModelMapper<ReportDTO, ReportViewModel> reportMapper;
        private readonly IMailer mailer;

        public AdminReportController(IReportService reportService,
            IViewModelMapper<ReportDTO, ReportViewModel> reportMapper,
            IToastNotification toastNotification, IMailer mailer)
        {
            this.reportService = reportService ?? throw new ArgumentNullException(nameof(reportService));
            this.toastNotification = toastNotification ?? throw new ArgumentNullException(nameof(toastNotification));
            this.reportMapper = reportMapper ?? throw new ArgumentNullException(nameof(reportMapper));
            this.mailer = mailer ?? throw new ArgumentNullException(nameof(mailer));
        }

        [HttpGet]
        public async Task<IActionResult> GetFullReportForApproval(int? id)
        {
            var fullReport = (await this.reportService.GetReportAsync(id));
            var report = this.reportMapper.MapFrom(fullReport);
            return View(report);
        }

        [HttpGet]
        public async Task<IActionResult> GetReportsForApproval()
        {
            var pendingReports = (await this.reportService.GetPendingReportsAsync());          
            var pendingReportsVM = this.reportMapper.MapFrom(pendingReports);
            ViewData["pendingReportsVM"] = pendingReportsVM;

            return View();
        }

        public async Task<IActionResult> ApproveReportConfirm(int? id)
        {
            try
            {
                var reports = await this.reportService.AproveReportAsync(id);
                this.toastNotification.AddInfoToastMessage("User will be notified by email from Insight Hub Team");
                this.toastNotification.AddSuccessToastMessage("Report was successfully approved");
                return RedirectToAction("GetReportsForApproval");
            }

            catch (Exception e)
            {
                this.toastNotification.AddWarningToastMessage(e.Message);
                return View();
            }
        }

        public async Task<IActionResult> RejectReportConfirm(int? id)
        {
            try
            {
                await this.reportService.RejectReportAsync(id);
                this.toastNotification.AddInfoToastMessage("User will be notified by email from Insight Hub Team");
                this.toastNotification.AddWarningToastMessage("The request for report approval was rejected");
                return RedirectToAction("GetReportsForApproval");
            }

            catch (Exception e)
            {
                this.toastNotification.AddWarningToastMessage(e.Message);
                return View();
            }
        }

        [HttpGet]
        public IActionResult GetReportsOfUser()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> GetReportsOfUser(int id)
        {
            try
            {
                var reports = await this.reportService.GetReportsOfUserAsync(id);
                var reportsVM = this.reportMapper.MapFrom(reports);
                return View(reportsVM);
            }

            catch (Exception)
            {
                this.toastNotification.AddWarningToastMessage("Oops! Something went wrong. Please try again");
                return View();
            }
        }

        [HttpGet]
        public async Task<IActionResult> FeaturedReports()
        {
            var reports = await this.reportService.GetAprovedReportsAsync();
            var reportsVM = this.reportMapper.MapFrom(reports);

            return View(reportsVM);
        }

        public async Task<IActionResult> FeatureReport(int? id)
        {
            try
            {
                var featureReport = await this.reportService.FeatureReportAsync(id);
                this.toastNotification.AddSuccessToastMessage("Report was successfully featured in Home Page");
                return RedirectToAction("FeaturedReports");
            }

            catch (Exception)
            {
                this.toastNotification.AddWarningToastMessage("Oops! Something went wrong. Please try again");
                return RedirectToAction("FeaturedReports");
            }
        }

        public async Task<IActionResult> StopFeaturingReport(int? id)
        {
            try
            {
                var report = await this.reportService.StopFeaturingReportAsync(id);
                this.toastNotification.AddSuccessToastMessage("Report was successfully removed from the Homepage");
                return RedirectToAction("FeaturedReports");
            }

            catch (Exception)
            {
                this.toastNotification.AddWarningToastMessage("Oops! Something went wrong. Please try again");
                return RedirectToAction("FeaturedReports");
            }
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound("Id cannot be null or empty");
            }

            var report = await this.reportService.GetReportAsync(id.Value);

            if (report == null)
            {
                return NotFound("Report cannot be null or empty");
            }

            return View(reportMapper.MapFrom(report));
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var report = await this.reportService.DeleteReportAsync(id);
            this.toastNotification.AddSuccessToastMessage("Report successfully deleted");
            return RedirectToAction("GetAllReports", "AnonymousReport");
        }
    }
}



 

InsightHub/InsightHub/Controllers/Common/CommonController.cs
using InsightHub.Web.WebMappers.Contracts;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using InsightHub.Services.Contracts;
using System.Collections.Generic;
using InsightHub.Services.DTOs;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Threading.Tasks;
using InsightHub.Web.Models;
using NToastNotify;
using System.Linq;
using System;

namespace InsightHub.Web.Controllers.Common
{
    public class CommonController : Controller
    {
        private readonly ITagService tagService;
        private readonly IReportService reportService;
        private readonly IIndustryService industryService;
        private readonly IToastNotification toastNotification;
        private readonly IViewModelMapper<TagDTO, TagViewModel> tagMapper;
        private readonly IViewModelMapper<ReportDTO, ReportViewModel> reportMapper;
        private readonly IViewModelMapper<IndustryDTO, IndustryViewModel> industryMapper;

        public CommonController(IReportService reportService,
            IViewModelMapper<ReportDTO, ReportViewModel> reportMapper,
            IViewModelMapper<IndustryDTO, IndustryViewModel> industryMapper,
            IToastNotification toastNotification, IIndustryService industryService,
            IViewModelMapper<TagDTO, TagViewModel> tagMapper, ITagService tagService)
        {
            this.toastNotification = toastNotification ?? throw new ArgumentNullException(nameof(toastNotification));
            this.industryService = industryService ?? throw new ArgumentNullException(nameof(industryService));
            this.industryMapper = industryMapper ?? throw new ArgumentNullException(nameof(industryMapper));
            this.reportService = reportService ?? throw new ArgumentNullException(nameof(reportService));
            this.reportMapper = reportMapper ?? throw new ArgumentNullException(nameof(reportMapper));
            this.tagService = tagService ?? throw new ArgumentNullException(nameof(tagService));
            this.tagMapper = tagMapper ?? throw new ArgumentNullException(nameof(tagMapper));
        }

        [HttpGet]
        [Authorize(Roles = "Admin, Author")]
        public async Task<IActionResult> CreateReport()

        {
            var tags = await tagService.GetAllTagsAsync();
            var tagsVM = this.tagMapper.MapFrom(tags);
            var selectList = new List<SelectListItem>();
            var tagsVMList = tagsVM.ToList();

            tagsVMList.ForEach(i => selectList.Add(new SelectListItem(i.Name, i.Id.ToString())));
            var mapToSelectList = new ReportViewModel() { Tags = selectList };

            ViewData["Id"] = new SelectList(await industryService.GetAllIndustries(), "Id", "Name");
            return View(mapToSelectList);
        }

        [HttpPost]
        [Authorize(Roles = "Author, Admin")]
        public async Task<IActionResult> CreateReport(ReportViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    this.toastNotification.AddErrorToastMessage("Model state is not valid.");
                    return RedirectToAction(nameof(CreateReport));
                }
                model.AuthorId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
                var modelToDTO = this.reportMapper.MapFrom(model);
                await this.reportService.CreateReportAsync(modelToDTO);

                this.toastNotification.AddSuccessToastMessage("Report successfully created. You will be notified " +
                    "by email from Insight Hub Team, when the report is approved");
                return RedirectToAction(nameof(CreateReport));
            }
            catch (Exception e)
            {
                this.toastNotification.AddErrorToastMessage(e.Message);
                return RedirectToAction(nameof(CreateReport));
            }
        }

        [HttpGet]
        [Authorize(Roles = "Author, Admin")]
        public async Task<IActionResult> UpdateReport(int? id)

        {
            var report = await reportService.GetReportAsync(id.Value);
            var tags = await tagService.GetAllTagsAsync();
            var tagsVM = this.tagMapper.MapFrom(tags);
            var selectList = new List<SelectListItem>();
            var tagsVMList = tagsVM.ToList();

            tagsVMList.ForEach(i => selectList.Add(new SelectListItem(i.Name, i.Id.ToString())));
            var mapToSelectList = new ReportViewModel() { Tags = selectList };

            ViewData["Id"] = new SelectList(await industryService.GetAllIndustries(), "Id", "Name");
            var reportVM = reportMapper.MapFrom(report);
            reportVM.Tags = selectList;
            ViewData["Model"] = reportVM;
            return View(reportVM);
        }

        [HttpPost]
        [Authorize(Roles = "Admin, Author")]
        public async Task<IActionResult> UpdateReport(int? id, ReportViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    ModelState.AddModelError(string.Empty, "Model state is not valid.");
                }

                var modelToDTO = this.reportMapper.MapFrom(model);
                await this.reportService.UpdateReportAsync(modelToDTO);
                this.toastNotification.AddSuccessToastMessage("Report successfully updated");
                return RedirectToAction(nameof(UpdateReport));
            }

            catch (Exception e)
            {
                this.toastNotification.AddErrorToastMessage(e.Message);
                return RedirectToAction(nameof(UpdateReport));
            }
        }

        [HttpGet]
        [Authorize(Roles = "Author, Admin")]
        public IActionResult CreateTag()

        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Author, Admin")]
        public async Task<IActionResult> CreateTag(TagViewModel model)
        {
            if (ModelState.IsValid)
            {
                var modelToDTO = this.tagMapper.MapFrom(model);
                await this.tagService.CreateTagAsync(modelToDTO);
                this.toastNotification.AddSuccessToastMessage("Tag successfully created");

                return RedirectToAction(nameof(CreateReport));
            }

            this.toastNotification.AddWarningToastMessage("Incorrect input, please try again");
            ModelState.AddModelError(string.Empty, "Model state is not valid.");
            return RedirectToAction("CreateTag");
        }

        [HttpGet]
        [Authorize(Roles = "Author, Admin")]
        public async Task<IActionResult> UpdateTagAsync(int? id)
        {
            try
            {
                var tag = await this.tagService.GetTagAsync(id.Value);
                var modelToDTO = this.tagMapper.MapFrom(tag);
                return View(modelToDTO);
            }
            catch (Exception)
            {
                this.toastNotification.AddWarningToastMessage("Oops! Something went wrong. Please try again");
                return View();
            }
        }

        [HttpPost]
        [Authorize(Roles = "Author, Admin")]
        public async Task<IActionResult> UpdateTag(TagViewModel model)
        {
            if (ModelState.IsValid)
            {
                var modelToDTO = this.tagMapper.MapFrom(model);
                await this.tagService.UpdateTagAsync(modelToDTO);
                this.toastNotification.AddSuccessToastMessage("Tag successfully updated");
                return RedirectToAction("GetAllTags", "AdminTag"); 
            }

            this.toastNotification.AddWarningToastMessage("Incorrect input, please try again");
            ModelState.AddModelError(string.Empty, "Model state is not valid.");
            return RedirectToAction("UpdateTag");
        }
    }
}

InsightHub/InsightHub/Views/AdminReport/Delete.cshtml
@model InsightHub.Web.Models.ReportViewModel

@{
    ViewData["Title"] = "Delete";
}

<style>
    .header-content {
        width: 1000px;
        margin-left: 400px;
    }

    h1 {
        text-align: center
    }

    h4 {
        text-align: center;
    }

    .btn {
    }
</style>

<h1>Delete</h1>
<h4>Are you sure you want to delete "@Model.Name"</h4>
<div>
    <hr />
    <dl class="row" style="justify-content: center;">
        <dd>
            <img src="~/images/Industries/@Html.DisplayFor(model =>model.IndustryImg)" style="height:500px;width:720px;" />
        </dd>
        <dt class="col-lg-8">
            @Html.DisplayNameFor(model => model.Summary)
        </dt>
        <dd class="col-lg-8">
            @Html.DisplayFor(model => model.Summary)
        </dd>
        <dt class="col-lg-8">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-lg-8">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-lg-8">
            @Html.DisplayNameFor(model => model.AuthorName)
        </dt>
        <dd class="col-lg-8">
            @Html.DisplayFor(model => model.AuthorName)
        </dd>
        <dt class="col-lg-8">
            @Html.DisplayNameFor(model => model.IndustryName)
        </dt>
        <dd class="col-lg-8">
            @Html.DisplayFor(model => model.IndustryName)
        </dd>
        <dt class="col-lg-8">
            @Html.DisplayNameFor(model => model.DownloadsCnt)
        </dt>
        <dd class="col-lg-8">
            @Html.DisplayFor(model => model.DownloadsCnt)
        </dd>
        <dt class="col-lg-8">
            @Html.DisplayNameFor(model => model.UploadedOn)
        </dt>
        <dd class="col-lg-8">
            @Html.DisplayFor(model => model.UploadedOn)
        </dd>
    </dl>

    <!-- Button trigger delete modal -->

    <div class="col text-center">
        <button type="button" class="btn btn-danger btn btn-default" data-name="@Model.Name" data-id="@Model.Id" id="deleteButton" data-toggle="modal" data-target="#exampleModal3">Delete</button>
    </div>

    <!-- Delete Modal -->
    <div class="modal fade" id="exampleModal3" tabindex="-1" role="dialog" aria-labelledby="exampleModal3Label" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModal3Label">
                        Are you sure that you want to delete this report: @Model.Name?
                        <br />
                        This option will delete data permanently and cannot be recovered!
                    </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form asp-controller="AdminReport" asp-action="Delete">
                        <input value="@Model.Id" name="Id" type="hidden" id="hiddenId" />
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Delete </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(function () {
        $(document).on('click', '#deleteButton', function () {
            let title = $(this).data("name");
            let formid = $(this).data("id");
            $("#examplemodal3").html("delete following report: " + title);
            $("#hiddenid").remove("value");
            $("#hiddenid").attr("value", formid);
        });
    });
</script>

<partial name="_GoBack" />

InsightHub/InsightHub/Views/AdminReport/FeaturedReports.cshtml
@model IEnumerable<InsightHub.Web.Models.ReportViewModel>

<style>
    .table tr {
        cursor: pointer;
    }

    .hiddenRow {
        padding: 0 4px !important;
        background-color: #eeeeee;
        font-size: 13px;
    }

    #table {
        pointer-events: none;
    }
</style>

<div class="container" style="display:contents">
    <br />
    <div style="width:90%; margin:0 auto;">
        <table id="search" data-toolbar="#toolbar" class="table table-striped table-bordered dt-responsive nowrap" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Report name</th>
                    <th id="table">Status</th>
                </tr>
            </thead>
        </table>
    </div>
</div>

<script>
    $(document).ready(function () {
        $("#search").DataTable({
            "processing": true, // for show progress bar
            "serverSide": true, // for process server side
            "filter": true, // this is for disable filter (search box)
            "orderMulti": false, // for disable multiple column at once

            "ajax": {
                "url": "/Search/LoadReports",
                "type": "POST",
                "dataSrc": "data"
            },
            "columnDef": [{
                "targets": [0],
                "visible": false,
                "searchable": false
            }],
            "columns": [

                { "data": "id", "name": "id", "autoWidth": true },
                { "data": "name", "name": "name", "autoWidth": true },

                {
                    data: "isFeatured",
                    render: function (data, type, full, meta) {
                        {
                            if
                                (data == false) {
                                {
                                    return '<a class="btn btn-success" href="/AdminReport/FeatureReport/' + full.id + '"><i class="fas fa-check-square">Feature</a>';
                                }
                            }
                            else {
                                return '<a class="btn btn-danger" href="/AdminReport/StopFeaturingReport/' + full.id + '"><i class="fas fa-minus-square">Stop Featuring</a>';
                            }
                        }
                    }
                },
            ]
        });
    });
</script>
<partial name="_GoBack" />
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

InsightHub/InsightHub/Views/AdminReport/GetFullReportForApproval.cshtml
@model InsightHub.Web.Models.ReportViewModel

<style>
    .header-content {
        width: 1000px;
        margin-left: 400px;
    }

    h1 {
        text-align: center
    }

    h4 {
        text-align: center;
    }

    .btn {
    }
</style>

<h1>Overview</h1>
<h4>"@Model.Name"</h4>
<h4>Available options</h4>

<!-- Button trigger approve modal -->
<div class="col text-center" style="margin-bottom: 10px;">
    <button type="button" class="btn btn-primary btn btn-default fas fa-check-circle" data-name="@Model.Name" data-id="@Model.Id" id="approveButton" data-toggle="modal" data-target="#exampleModal3">Approve</button>
</div>

<!-- Approve Modal -->
<div class="modal fade" id="exampleModal3" tabindex="-1" role="dialog" aria-labelledby="exampleModal3Label" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModal3Label">
                    Are you sure you want to confirm : @Model.Name?
                    <br />
                    After approving report will be converted to PDF and upload to Azure Blob storage.
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form asp-controller="AdminReport" asp-action="ApproveReportConfirm">
                    <input value="@Model.Id" name="Id" type="hidden" id="hiddenId" />
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Approve</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Button trigger approve modal -->
<div class="col text-center" style="margin-bottom: 10px;">
    <button type="button" class="btn btn-danger btn btn-default fas fa-times-circle" data-name="@Model.Name" data-id="@Model.Id" id="rejectButton" data-toggle="modal" data-target="#exampleModal2">Reject</button>
</div>

<!-- Reject Modal -->
<div class="modal fade" id="exampleModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModal2Label" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModal2Label">
                    Are you sure you want to reject : @Model.Name?
                    <br />
                    This action cannot be undone!
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form asp-controller="AdminReport" asp-action="RejectReportConfirm">
                    <input value="@Model.Id" name="Id" type="hidden" id="hiddenId" />
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Reject</button>
                </form>
            </div>
        </div>
    </div>
</div>

<form>
    <div class="col text-center">
        <a asp-controller="Common" asp-action="UpdateReport" asp-route-id="@Model.Id" style="text-decoration:none" class="btn btn-success btn btn-default fas fa-user-check">Edit</a>
    </div>
</form>

<div>
    <hr />
    <dl class="row" style="justify-content: center;">
        <dd>
            <img src="~/images/Industries/@Html.DisplayFor(model =>model.IndustryImg)" style="height:500px;width:720px;" />
        </dd>
        <dt class="col-lg-8">
            @Html.DisplayNameFor(model => model.Summary)
        </dt>
        <dd class="col-lg-8">
            @Html.DisplayFor(model => model.Summary)
        </dd>
        <dt class="col-lg-8">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-lg-8">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-lg-8">
            @Html.DisplayNameFor(model => model.AuthorName)
        </dt>
        <dd class="col-lg-8">
            @Html.DisplayFor(model => model.AuthorName)
        </dd>
        <dt class="col-lg-8">
            @Html.DisplayNameFor(model => model.IndustryName)
        </dt>
        <dd class="col-lg-8">
            @Html.DisplayFor(model => model.IndustryName)
        </dd>
        <dt class="col-lg-8">
            @Html.DisplayNameFor(model => model.DownloadsCnt)
        </dt>
        <dd class="col-lg-8">
            @Html.DisplayFor(model => model.DownloadsCnt)
        </dd>
        <dt class="col-lg-8">
            @Html.DisplayNameFor(model => model.UploadedOn)
        </dt>
        <dd class="col-lg-8">
            @Html.DisplayFor(model => model.UploadedOn)
        </dd>
    </dl>
</div>
<script>
    $(function () {
        $(document).on('click', '#approveButton', function () {
            let title = $(this).data("name");
            let formid = $(this).data("id");
            $("#examplemodal3").html("approve following report: " + title);
            $("#hiddenid").remove("value");
            $("#hiddenid").attr("value", formid);
        });
    });

    $(function () {
        $(document).on('click', '#rejectButton', function () {
            let title = $(this).data("name");
            let formid = $(this).data("id");
            $("#examplemodal2").html("reject following report: " + title);
            $("#hiddenid").remove("value");
            $("#hiddenid").attr("value", formid);
        });
    });
</script>

InsightHub/InsightHub/Views/AdminReport/GetReportsForApproval.cshtml
@model IEnumerable<InsightHub.Web.Models.ReportViewModel>

<style>
    .table tr {
        cursor: pointer;
    }

    .hiddenRow {
        padding: 0 4px !important;
        background-color: #eeeeee;
        font-size: 13px;
    }

    #table {
        pointer-events: none;
    }
</style>

<div class="container" style="display:contents">
    <br />
    <div style="width:90%; margin:0 auto;">
        <table id="search" data-toolbar="#toolbar" class="table table-striped table-bordered dt-responsive nowrap" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Report name</th>
                    <th>Created by</th>
                    <th id="table">Details</th>
                </tr>
            </thead>
        </table>
    </div>
</div>
<partial name="_GoBack" />
<script>
    $(document).ready(function () {
        $("#search").DataTable({
            "processing": true, // for show progress bar
            "serverSide": true, // for process server side
            "filter": true, // this is for disable filter (search box)
            "orderMulti": false, // for disable multiple column at once

            "ajax": {
                "url": "/Search/LoadReportsForApproval",
                "type": "POST",
                "dataSrc": "data"
            },
            "columnDef": [{
                "targets": [0],
                "visible": false,
                "searchable": false
            }],
            "columns": [

                { "data": "id", "name": "id", "autoWidth": true },
                { "data": "name", "name": "name", "autoWidth": true },
                { "data": "authorName", "name": "authorName", "autoWidth": true },

                 {
                    data: null,
                    render: function (data, type, full, meta) {
                        { return '<a class="btn btn-danger" href="/AdminReport/GetFullReportForApproval/' + full.id + '"><i class="fas fa-user-times">View Report</a>'; }
                    }
                },
            ]
        });
    });
</script>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}